// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: dmail.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DmailPacket struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                                          // Protocol version (currently 1)
	RecipientPubkey  []byte                 `protobuf:"bytes,2,opt,name=recipient_pubkey,json=recipientPubkey,proto3" json:"recipient_pubkey,omitempty"`    // 32-byte Ed25519 public key
	SenderPubkey     []byte                 `protobuf:"bytes,3,opt,name=sender_pubkey,json=senderPubkey,proto3" json:"sender_pubkey,omitempty"`             // 32-byte Ed25519 public key
	Timestamp        uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                      // Unix timestamp in seconds
	PowNonce         uint64                 `protobuf:"varint,5,opt,name=pow_nonce,json=powNonce,proto3" json:"pow_nonce,omitempty"`                        // The nonce that solves the Hashcash puzzle
	PowDifficulty    uint32                 `protobuf:"varint,6,opt,name=pow_difficulty,json=powDifficulty,proto3" json:"pow_difficulty,omitempty"`         // Number of leading zero bits required (e.g., 20)
	EncryptedPayload []byte                 `protobuf:"bytes,7,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"` // XSalsa20-Poly1305 encrypted bytes
	Signature        []byte                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`                                       // 64-byte Ed25519 signature of fields 1-7
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DmailPacket) Reset() {
	*x = DmailPacket{}
	mi := &file_dmail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DmailPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmailPacket) ProtoMessage() {}

func (x *DmailPacket) ProtoReflect() protoreflect.Message {
	mi := &file_dmail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmailPacket.ProtoReflect.Descriptor instead.
func (*DmailPacket) Descriptor() ([]byte, []int) {
	return file_dmail_proto_rawDescGZIP(), []int{0}
}

func (x *DmailPacket) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DmailPacket) GetRecipientPubkey() []byte {
	if x != nil {
		return x.RecipientPubkey
	}
	return nil
}

func (x *DmailPacket) GetSenderPubkey() []byte {
	if x != nil {
		return x.SenderPubkey
	}
	return nil
}

func (x *DmailPacket) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DmailPacket) GetPowNonce() uint64 {
	if x != nil {
		return x.PowNonce
	}
	return 0
}

func (x *DmailPacket) GetPowDifficulty() uint32 {
	if x != nil {
		return x.PowDifficulty
	}
	return 0
}

func (x *DmailPacket) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *DmailPacket) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`   // UUID generated by sender
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`                        // Plaintext subject
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`                              // Plaintext body (Markdown supported)
	ReplyToId     string                 `protobuf:"bytes,4,opt,name=reply_to_id,json=replyToId,proto3" json:"reply_to_id,omitempty"` // Optional: ID of the message being replied to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_dmail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_dmail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_dmail_proto_rawDescGZIP(), []int{1}
}

func (x *Payload) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Payload) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Payload) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Payload) GetReplyToId() string {
	if x != nil {
		return x.ReplyToId
	}
	return ""
}

type NameRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                         // Lowercase name, e.g. "alice"
	Pubkey        []byte                 `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`                                     // 32-byte Ed25519 public key
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                              // Registration time (Unix seconds)
	PowNonce      uint64                 `protobuf:"varint,4,opt,name=pow_nonce,json=powNonce,proto3" json:"pow_nonce,omitempty"`                // PoW nonce for name registration
	PowDifficulty uint32                 `protobuf:"varint,5,opt,name=pow_difficulty,json=powDifficulty,proto3" json:"pow_difficulty,omitempty"` // Leading zero bits required (e.g., 28)
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                               // Ed25519 signature of fields 1-5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameRecord) Reset() {
	*x = NameRecord{}
	mi := &file_dmail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameRecord) ProtoMessage() {}

func (x *NameRecord) ProtoReflect() protoreflect.Message {
	mi := &file_dmail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameRecord.ProtoReflect.Descriptor instead.
func (*NameRecord) Descriptor() ([]byte, []int) {
	return file_dmail_proto_rawDescGZIP(), []int{2}
}

func (x *NameRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NameRecord) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *NameRecord) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NameRecord) GetPowNonce() uint64 {
	if x != nil {
		return x.PowNonce
	}
	return 0
}

func (x *NameRecord) GetPowDifficulty() uint32 {
	if x != nil {
		return x.PowDifficulty
	}
	return 0
}

func (x *NameRecord) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_dmail_proto protoreflect.FileDescriptor

const file_dmail_proto_rawDesc = "" +
	"\n" +
	"\vdmail.proto\x12\x05dmail\"\xa4\x02\n" +
	"\vDmailPacket\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12)\n" +
	"\x10recipient_pubkey\x18\x02 \x01(\fR\x0frecipientPubkey\x12#\n" +
	"\rsender_pubkey\x18\x03 \x01(\fR\fsenderPubkey\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x1b\n" +
	"\tpow_nonce\x18\x05 \x01(\x04R\bpowNonce\x12%\n" +
	"\x0epow_difficulty\x18\x06 \x01(\rR\rpowDifficulty\x12+\n" +
	"\x11encrypted_payload\x18\a \x01(\fR\x10encryptedPayload\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\"v\n" +
	"\aPayload\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1e\n" +
	"\vreply_to_id\x18\x04 \x01(\tR\treplyToId\"\xb8\x01\n" +
	"\n" +
	"NameRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\fR\x06pubkey\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x1b\n" +
	"\tpow_nonce\x18\x04 \x01(\x04R\bpowNonce\x12%\n" +
	"\x0epow_difficulty\x18\x05 \x01(\rR\rpowDifficulty\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignatureB*Z(github.com/ehoneahobed/dmail/internal/pbb\x06proto3"

var (
	file_dmail_proto_rawDescOnce sync.Once
	file_dmail_proto_rawDescData []byte
)

func file_dmail_proto_rawDescGZIP() []byte {
	file_dmail_proto_rawDescOnce.Do(func() {
		file_dmail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dmail_proto_rawDesc), len(file_dmail_proto_rawDesc)))
	})
	return file_dmail_proto_rawDescData
}

var file_dmail_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dmail_proto_goTypes = []any{
	(*DmailPacket)(nil), // 0: dmail.DmailPacket
	(*Payload)(nil),     // 1: dmail.Payload
	(*NameRecord)(nil),  // 2: dmail.NameRecord
}
var file_dmail_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dmail_proto_init() }
func file_dmail_proto_init() {
	if File_dmail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dmail_proto_rawDesc), len(file_dmail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dmail_proto_goTypes,
		DependencyIndexes: file_dmail_proto_depIdxs,
		MessageInfos:      file_dmail_proto_msgTypes,
	}.Build()
	File_dmail_proto = out.File
	file_dmail_proto_goTypes = nil
	file_dmail_proto_depIdxs = nil
}
